version: "3.0"

services:
  member-backend:
    container_name: member-backend
    image: member-backend
    build: .
    ports:
      - "7251:3000"
    volumes:
      - .:/home/app/member-backend
      - /home/app/member-backend/dist
      - /home/app/member-backend/node_modules
      - /home/app/member-backend/.git
      - /home/app/member-backend/.vscode
      - /home/app/member-backend/.npm
    environment:
      - NODE_ENV=development
    entrypoint: /home/app/member-backend/docker-entrypoint.sh
    networks:
      - micro-service

networks:
  micro-service:
    external: true
    name: micro-service