version: "3.0"

services:
  member_backend:
    container_name: member_backend
    image: member_backend
    build: .
    ports:
      - "7251:3000"
      - "8452:9229"
    volumes:
      - member-backend:/home/app/member-backend
      - .:/home/app/member-backend
      - /home/app/member-backend/node_modules
      - /home/app/member-backend/.git
      - /home/app/member-backend/.vscode
    environment:
      - NODE_ENV=development
    command: npm run start:debug
    networks:
      - micro-service

networks:
  micro-service:
    external: true

volumes:
  member-backend:
    external: true